version: '3.8'


services:
  db:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      PG_PASSWORD: test
      POSTGRES_DB: scroll_db


volumes:
  postgres_data:
